#!/usr/bin/env python3
"""Generate llms-full.txt by concatenating all LTspice reference docs.

llms-full.txt is the single-file, full-text bundle of the entire reference set,
intended for one-shot ingestion by an LLM. Regenerate it after editing any
reference file:

    python generate_llms_full.py

The script strips each file's YAML frontmatter and the "[<- AI Reference]"
back-link, then joins the bodies with separators. Ordering follows the reading
order in ai_ref/README.md.
"""
import re
from pathlib import Path

# Reading order mirrors the Reference Files table in ai_ref/README.md.
FILES = [
    "README.md",
    "LTSPICE-QUICKSTART.md",
    "LTSPICE-KEYBOARD-SHORTCUTS.md",
    "LTSPICE-MENU-REFERENCE.md",
    "SPICE-SYNTAX-REFERENCE.md",
    "CIRCUIT-ELEMENTS-REFERENCE.md",
    "SIMULATION-COMMANDS-REFERENCE.md",
    "TROUBLESHOOTING-GUIDE.md",
    "SCHEMATIC-REFERENCE.md",
    "WAVEFORM-VIEWER-GUIDE.md",
    "DEVICE-MODELS-GUIDE.md",
    "MEASURE-DATABASE-REFERENCE.md",
    "MEAS-REFERENCE.md",
    "FAQ-AND-TIPS.md",
    "ADI-DESIGN-TOOLS-REFERENCE.md",
]

HEADER = """# LTspice Reference — Full Text

> Complete, concatenated text of the LTspice reference documentation from Analog
> Devices, assembled for single-pass ingestion by AI assistants. Each section
> below is one source file from the ai_ref/ directory, in reading order.
>
> Conventions: `1M` means milli (1e-3), not mega — use `1Meg`. Always write micro
> as `u` (1e-6), never the `mu` symbol. Node `0` is ground; `GND` is a synonym.
>
> This file is generated by generate_llms_full.py. Do not edit it by hand; edit
> the source files in ai_ref/ and regenerate.
"""


def strip_frontmatter(text: str) -> str:
    """Remove a leading YAML frontmatter block delimited by '---' lines."""
    if text.startswith("---"):
        end = text.find("\n---", 3)
        if end != -1:
            nl = text.find("\n", end + 1)
            text = text[nl + 1:] if nl != -1 else ""
    return text


def strip_backlink(text: str) -> str:
    """Drop the '[<- AI Reference](README.md)' / '[<- Home]' back-link line."""
    lines = text.splitlines()
    while lines and (not lines[0].strip() or lines[0].lstrip().startswith("[←")):
        lines.pop(0)
    return "\n".join(lines)


def strip_toc(text: str) -> str:
    """Drop a '## Table of Contents' section.

    The in-document ToC is a list of anchor links useful on the rendered site
    but pure noise for single-pass AI ingestion (it produces a low-value chunk
    of bare links). Remove from the start of the heading through to the next
    same-or-higher-level heading.
    """
    lines = text.splitlines()
    out, i = [], 0
    while i < len(lines):
        if re.match(r"^##\s+Table of Contents\s*$", lines[i], re.IGNORECASE):
            i += 1
            while i < len(lines) and not re.match(r"^#{1,2}\s+", lines[i]):
                i += 1
            continue
        out.append(lines[i])
        i += 1
    return "\n".join(out)


def main() -> None:
    root = Path(__file__).resolve().parent
    ai_ref = root / "ai_ref"
    parts = [HEADER.rstrip() + "\n"]

    for name in FILES:
        path = ai_ref / name
        if not path.exists():
            raise SystemExit(f"Missing source file: {path}")
        body = strip_toc(strip_backlink(strip_frontmatter(path.read_text(encoding="utf-8")))).strip()
        parts.append("\n\n---\n\n")
        parts.append(f"<!-- source: ai_ref/{name} -->\n\n")
        parts.append(body + "\n")

    out = root / "llms-full.txt"
    # newline="\n" keeps the bundle LF-only on every platform; without it Windows
    # translates every \n to \r\n and rewrites the whole file.
    out.write_text("".join(parts), encoding="utf-8", newline="\n")
    print(f"Wrote {out} ({out.stat().st_size} bytes) from {len(FILES)} files.")


if __name__ == "__main__":
    main()
